Repository mary0L/Hustle-Hamster, pull requests merged in 2024-10, with the labels that each got.

#80 Extended input handling
  Hustle-Hamster/includes/utils.h
  Hustle-Hamster/utils.cpp
Labels: extension, User Testing

#83 Implementing user testing
  Hustle-Hamster/hammyDialogue.cpp
  Hustle-Hamster/utils.cpp
Labels: User Testing

#88 Removing all the code for mac development
  Hustle-Hamster/includes/Journal.h
  Hustle-Hamster/includes/menuHelp.h
  Hustle-Hamster/includes/utils.h
  Hustle-Hamster/main.cpp
  Hustle-Hamster/menuHelp.cpp
  Hustle-Hamster/utils.cpp
Labels: refactoring

#89 Adding development reflection
  Hustle-Hamster/Journal.cpp
  Hustle-Hamster/main
  README.md
Labels: documentation
