Repository mary0L/Hustle-Hamster, pull requests merged in 2024-08, with the labels that each got.

#12 Adding preprocessor directive to not include some win32 bulk
  Hustle-Hamster/main.cpp
Labels: bugfix

#14 Utils refactoring
  .gitignore
  Hustle-Hamster/CMakeLists.txt
  Hustle-Hamster/main.cpp
  Hustle-Hamster/utils.cpp
  Hustle-Hamster/utils.h
Labels: refactoring

#16 Making changes based on Codacy suggestions
  Hustle-Hamster/Journal.cpp
  Hustle-Hamster/Journal.h
Labels: refactoring

#20 Menu implementation
  Hustle-Hamster/CMakeLists.txt
  Hustle-Hamster/dailyLog.cpp
  Hustle-Hamster/dailyLog.h
  Hustle-Hamster/main.cpp
  Hustle-Hamster/menuHelp.cpp
  Hustle-Hamster/menuHelp.h
  Hustle-Hamster/utils.cpp
  Hustle-Hamster/utils.h
Labels: refactoring, bugfix

#26 Adding Doxygen Comments
  Hustle-Hamster/Date.h
  Hustle-Hamster/Journal.cpp
  Hustle-Hamster/Journal.h
  Hustle-Hamster/dailyLog.h
  Hustle-Hamster/main.cpp
  Hustle-Hamster/menuHelp.h
  Hustle-Hamster/utils.h
Labels: documentation

#32 Changing the console character encoding
  Hustle-Hamster/main.cpp
Labels: bugfix

#33 Adding file doxygen comments to the classes
  Hustle-Hamster/Date.h
  Hustle-Hamster/Journal.h
Labels: documentation
