Repository mary0L/Hustle-Hamster, pull requests merged in 2024-09, with the labels that each got.

#42 Journal export
  Hustle-Hamster/utils.cpp
Labels: refactoring, bugfix

#49 46 add method to journal to check if an activity has been done
  Hustle-Hamster/Journal.cpp
  Hustle-Hamster/Journal.h
Labels: extension

#47 Journal export
  Hustle-Hamster/utils.cpp
  Hustle-Hamster/utils.h
Labels: refactoring, bugfix

#43 User can input when hammy is speaking
  Hustle-Hamster/dailyLog.cpp
  Hustle-Hamster/main.cpp
  Hustle-Hamster/menuHelp.cpp
  Hustle-Hamster/utils.cpp
  Hustle-Hamster/utils.h
  README.md
Labels: bugfix

#50 44 add random no generator to utils
  Hustle-Hamster/utils.cpp
  Hustle-Hamster/utils.h
  README.md
Labels: feature

#54 53 hammy should have varying responses
  Hustle-Hamster/CMakeLists.txt
  Hustle-Hamster/dailyLog.cpp
  Hustle-Hamster/feedback.cpp
  Hustle-Hamster/hammyDialogue.cpp
  Hustle-Hamster/hammyDialogue.h
  Hustle-Hamster/main.cpp
  Hustle-Hamster/menuHelp.cpp
  Hustle-Hamster/menuHelp.h
  Hustle-Hamster/utils.cpp
  Hustle-Hamster/utils.h
Labels: feature, refactoring, extension

#55 25 create directory for exported journals
  Hustle-Hamster/utils.cpp
  Hustle-Hamster/utils.h
Labels: feature, extension

#67 hammy now asks user if they want to change any inputs before saving a…
  Hustle-Hamster/Journal.cpp
  Hustle-Hamster/dailyLog.cpp
  Hustle-Hamster/includes/Journal.h
  Hustle-Hamster/includes/dailyLog.h
Labels: feature, bugfix, User Testing

#69 Checks for existing journal entries from the day, and also checks on entry whether the app has been used before
  Hustle-Hamster/dailyLog.cpp
  Hustle-Hamster/includes/Journal.h
  Hustle-Hamster/includes/menuHelp.h
  Hustle-Hamster/includes/utils.h
  Hustle-Hamster/main.cpp
  Hustle-Hamster/menuHelp.cpp
  Hustle-Hamster/utils.cpp
Labels: extension

#71 68 refactor input checking into individual methods
  Hustle-Hamster/dailyLog.cpp
  Hustle-Hamster/includes/utils.h
  Hustle-Hamster/menuHelp.cpp
  Hustle-Hamster/utils.cpp
Labels: refactoring
